name: GitHub Actions Demo
on: [push]
jobs:
  check-cmake-build:
    runs-on: ubuntu-latest
    steps:
      - run:  sudo apt-get update
      - run:  sudo apt-get upgrade
      - run: sudo apt-get install gcc -y
      - run: sudo apt-get install g++ -y
      - run: sudo apt-get install make -y
      - run: sudo apt-get install cmake -y
      - run: sudo apt-get install libboost-test-dev -y
      - name: checkout
        uses: actions/checkout@v2
      - run : echo ${{ github.workspace }}
      - run : mkdir build
      - run : cd build && cmake ../ -DPATCH_VERSION=${{ github.run_number }}
      - run : cd build && cmake --build .
      - run : cd build && cmake --build . --target test
      - run : cd build && cmake --build . --target package
      - uses : "marvinpinto/action-automatic-releases@latest"
        name : Create a Release
        with :
          repo_token : "${{ secrets.GITHUB_TOKEN }}"
          prerelease : false
          automatic_release_tag: ${{ github.run_number }}
